# Generated by Django 2.2 on 2019-09-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190831_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/media/image/%Y/%m', verbose_name='头像'),
        ),
    ]
